apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-config-controller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "delete", "create", "update", "list", "patch", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineconfignodes", "machineconfignodes/status"]
  verbs: ["create", "update", "patch", "get"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineconfigpools", "machineconfigpools/status"]
  verbs: ["list", "update", "get", "watch", "create"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineconfigs"]
  verbs: ["create", "get",  "delete", "list", "update", "watch"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["containerruntimeconfigs","containerruntimeconfigs/status"]
  verbs: ["get", "update", "patch", "list", "watch"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["kubeletconfigs","kubeletconfigs/status"]
  verbs: ["list", "get", "update", "patch", "watch"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["controllerconfigs","controllerconfigs/status"]
  verbs: ["get", "update","list", "watch", "create"]
- apiGroups: ["config.openshift.io"]
  resources: ["images"]
  verbs: ["get", "patch", "list", "deletecollection", "create"]
- apiGroups: ["config.openshift.io"]
  resources: ["clusterversions","clusterversions/status"]
  verbs: ["create", "get", "update", "list", "deletecollection"]
- apiGroups: ["config.openshift.io"]
  resources: ["featuregates", "featuregates/status"]
  verbs: ["get","update", "list", "deletecollection", "create"]
- apiGroups: ["config.openshift.io"]
  resources: ["nodes", "nodes/status"]
  verbs: ["list", "deletecollection", "get", "create", "update", "watch"]
- apiGroups: ["config.openshift.io"]
  resources: ["schedulers", "apiservers", "infrastructures", "imagedigestmirrorsets", "imagetagmirrorsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["operator.openshift.io"]
  resources: ["imagecontentsourcepolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["operator.openshift.io"]
  resources: ["etcds"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["daemonsets"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get"]
- apiGroups: ["machine.openshift.io"]
  resources: ["machinesets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - "*"
