name: machine-config-daemon-firstboot.service
enabled: true
contents: |
  [Unit]
  Description=Machine Config Daemon Firstboot
  # Make sure it runs only on OSTree booted system
  ConditionPathExists=/run/ostree-booted
  # Removal of this file signals firstboot completion
  ConditionPathExists=/etc/ignition-machine-config-encapsulated.json
  After=machine-config-daemon-pull.service
  Before=kubelet-dependencies.target

  [Service]
  Type=oneshot
  RemainAfterExit=yes
  # Disable existing repos (if any) so that OS extensions would use embedded RPMs only
  ExecStartPre=-/usr/bin/sh -c "sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/*.repo"
  # Run this via podman because we want to use the nmstatectl binary in our container
  ExecStart=/usr/bin/podman run --rm --privileged --net=host -v /:/rootfs  --entrypoint machine-config-daemon '{{ .Images.machineConfigOperator }}' firstboot-complete-machineconfig --persist-nics
  ExecStart=/usr/bin/podman run --rm --privileged --pid=host --net=host -v /:/rootfs  --entrypoint machine-config-daemon '{{ .Images.machineConfigOperator }}' firstboot-complete-machineconfig
  {{if .Proxy -}}
  EnvironmentFile=/etc/mco/proxy.env
  {{end -}}

  [Install]
  RequiredBy=firstboot-osupdate.target
